name: booking-order-app # change this to your app name
services:
  field-service: # change this to your service name
    container_name: field-service # change this to your service name
#    image: eggnocent/field-service:3 # change this to your image name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:8004" # change this to your port
    env_file:
      - .env
    networks:
      - local-network

networks:
  local-network:
    external: true